// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8uo4QWEBQZ-JLD22JH_TEtH8tnUH4E9g',
    appId: '1:801891116344:web:d79d75d39d1ecc0b8a8dcd',
    messagingSenderId: '801891116344',
    projectId: 'attendify-nishant',
    authDomain: 'attendify-nishant.firebaseapp.com',
    storageBucket: 'attendify-nishant.firebasestorage.app',
    measurementId: 'G-YHFFGMZ27H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOWSaa_AkP9ksh4NzQkaAZ7JI_JA2IxL0',
    appId: '1:801891116344:android:3aa987f105634ee78a8dcd',
    messagingSenderId: '801891116344',
    projectId: 'attendify-nishant',
    storageBucket: 'attendify-nishant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCilQr_7LOsAU-pzBNJyhqRHnubcV6YZuA',
    appId: '1:801891116344:ios:31e07b5e5f5d20cd8a8dcd',
    messagingSenderId: '801891116344',
    projectId: 'attendify-nishant',
    storageBucket: 'attendify-nishant.firebasestorage.app',
    iosBundleId: 'com.example.attendanceFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCilQr_7LOsAU-pzBNJyhqRHnubcV6YZuA',
    appId: '1:801891116344:ios:31e07b5e5f5d20cd8a8dcd',
    messagingSenderId: '801891116344',
    projectId: 'attendify-nishant',
    storageBucket: 'attendify-nishant.firebasestorage.app',
    iosBundleId: 'com.example.attendanceFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8uo4QWEBQZ-JLD22JH_TEtH8tnUH4E9g',
    appId: '1:801891116344:web:56072ea192bdf8168a8dcd',
    messagingSenderId: '801891116344',
    projectId: 'attendify-nishant',
    authDomain: 'attendify-nishant.firebaseapp.com',
    storageBucket: 'attendify-nishant.firebasestorage.app',
    measurementId: 'G-X26GKQ6FSF',
  );
}
